language: node_js
node_js:
  - 6
  - 8
sudo: false
install:
  - npm install -g codecov
cache:
  yarn: true
  directories:
    - node_modules
script:
  # Run test script
  - "yarn run lint"
  - "scripts/is-it-pretty.sh"
  - "yarn test -- --maxWorkers=4"
after_script:
  - codecov
